---
abstract: 'FusionInventory unified Agent for UNIX, Linux, Windows and MacOSX'
build_requires:
  ExtUtils::MakeMaker: 6.59
  HTTP::Proxy: 0
  HTTP::Server::Simple: 0
  HTTP::Server::Simple::Authen: 0
  IO::Capture::Stderr: 0
  IO::Socket::SSL: 0
  IPC::Run: 0
  JSON: 0
  LWP::Protocol::https: 0
  Net::SNMP: 0
  POE::Component::Client::Ping: 0
  Test::Compile: 0
  Test::Deep: 0
  Test::Exception: 0
  Test::HTTP::Server::Simple: 0
  Test::MockModule: 0
  Test::MockObject: 0
  Test::More: 0.93
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: FusionInventory-Agent
no_index:
  directory:
    - inc
    - share
    - t
recommends:
  Archive::Extract: 0
  Compress::Zlib: 0
  Crypt::DES: 0
  Digest::MD5: 0
  Digest::SHA: 0
  File::Copy::Recursive: 0
  HTTP::Daemon: 0
  IO::Socket::SSL: 0
  JSON: 0
  LWP::Protocol::https: 0
  Net::CUPS: 0.6
  Net::NBName: 0
  Net::SNMP: 0
  Net::Write::Layer2: 0
  POE::Component::Client::Ping: 0
  Parse::EDID: 0
  Proc::Daemon: 0
  Proc::PID::File: 0
  URI::Escape: 0
requires:
  File::Which: 0
  LWP: 5.8
  Net::IP: 0
  Socket::GetAddrInfo: 0
  Text::Template: 0
  UNIVERSAL::require: 0
  XML::TreePP: 0.26
  perl: 5.8.0
resources:
  license: http://opensource.org/licenses/gpl-license.php
  repository: https://github.com/fusinv/fusioninventory-agent
version: 2.3.5.1
