---
abstract: 'FusionInventory unified Agent for UNIX, Linux, Windows and MacOSX'
build_requires:
  ExtUtils::MakeMaker: 6.59
  HTTP::Proxy: 0
  HTTP::Server::Simple: 0
  HTTP::Server::Simple::Authen: 0
  IO::Capture::Stderr: 0
  IO::Socket::SSL: 0
  IPC::Run: 0
  LWP::Protocol::https: 0
  Test::Exception: 0
  Test::MockModule: 0
  Test::More: 0.93
  YAML: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: FusionInventory-Agent
no_index:
  directory:
    - inc
    - share
    - t
recommends:
  Compress::Zlib: 0
  HTTP::Daemon: 0
  IO::Socket::SSL: 0
  LWP::Protocol::https: 0
  Net::CUPS: 0.6
  Proc::Daemon: 0
  Proc::PID::File: 0
requires:
  File::Which: 0
  LWP: 5.8
  Net::IP: 0
  Text::Template: 0
  UNIVERSAL::require: 0
  XML::TreePP: 0.26
  perl: 5.8.0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 2.2.6
